//
// Version.h
//
//
#ifndef SDK_VERSIONS
#define SDK_VERSIONS



#define   FIREBASEANALYICS   " FIREBASE/ANALYICS : 6.20.0"
#define  FIREBASECORE   "FIREBASE/CORE : 6.20.0"
#define  FIREBASECOREONLY   "FIREBASE/COREONLY : 6.20.0"
#define  FIREBASECRASHLYICS   "FIREBASE/CRASHLYICS : 6.20.0"
#define  FIREBASEANALYICS   "FIREBASEANALYICS : 6.3.1"
#define  FIREBASEANALYICSINEROP   "FIREBASEANALYICSINEROP : 1.5.0"
#define  FIREBASECORE   "FIREBASECORE : 6.6.4"
#define  FIREBASECOREDIAGNOSICS   "FIREBASECOREDIAGNOSICS : 1.2.2"
#define  FIREBASECOREDIAGNOSICSINEROP   "FIREBASECOREDIAGNOSICSINEROP : 1.2.0"
#define  FIREBASEINSALLAIONS   "FIREBASEINSALLAIONS : 1.1.0"
#define  GOOGLEAPPMEASUREMEN   "GOOGLEAPPMEASUREMEN : 6.3.1"
#define  GOOGLEDAATRANSPOR   "GOOGLEDAATRANSPOR : 5.0.0"
#define  GOOGLEDAATRANSPORCCTSUPPOR   "GOOGLEDAATRANSPORCCTSUPPOR : 2.0.0"
#define  GOOGLEUILIIESAPPDELEGAESWIZZLER   "GOOGLEUILIIES/APPDELEGAESWIZZLER : 6.5.2"
#define  GOOGLEUILIIESENVIRONMEN   "GOOGLEUILIIES/ENVIRONMEN : 6.5.2"
#define  GOOGLEUILIIESLOGGER   "GOOGLEUILIIES/LOGGER : 6.5.2"
#define  GOOGLEUILIIESMEHODSWIZZLER   "GOOGLEUILIIES/MEHODSWIZZLER : 6.5.2"
#define  GOOGLEUILIIESNEWORK   "GOOGLEUILIIES/NEWORK : 6.5.2"
#define  GOOGLEUILIIESNSDAAZLIB   "GOOGLEUILIIES/NSDAA+ZLIB : 6.5.2"
#define  GOOGLEUILIIESREACHABILIY   "GOOGLEUILIIES/REACHABILIY : 6.5.2"
#define  GOOGLEUILIIESUSERDEFAULS   "GOOGLEUILIIES/USERDEFAULS : 6.5.2"
#define  INDOORLOCAION   "INDOORLOCAION : 1.0.4"
#define  MAPBOXIOSSDK   "MAPBOXIOSSDK : 5.7.0"
#define  MAPBOXMOBILEEVENS   "MAPBOXMOBILEEVENS : 0.10.2"
#define  MAPWIZESDK   "MAPWIZESDK : 3.0.16"
#define  MAPWIZEUI   "MAPWIZEUI : 2.1.7"
#define  NANOPB   "NANOPB : 0.3.9011"
#define  NANOPBDECODE   "NANOPB/DECODE : 0.3.9011"
#define  NANOPBENCODE   "NANOPB/ENCODE : 0.3.9011"
#define  NAOSDK   "NAOSDK : 4.8.0"
#define  PROMISESOBJC   "PROMISESOBJC : 1.2.8"
#define  SSZIPARCHIVE   "SSZIPARCHIVE : 2.2.2"



#endif // SDK_VERSIONS
